// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWekhnjJkt6jCuhu8eKnVR5xtXO1XpcOw',
    appId: '1:1048947692024:web:9234f9b203a3585c28860d',
    messagingSenderId: '1048947692024',
    projectId: 'test-ff414',
    authDomain: 'test-ff414.firebaseapp.com',
    storageBucket: 'test-ff414.firebasestorage.app',
    measurementId: 'G-MJF3M3VPCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgJRdesXoDMZyZpF-zuo0Xsdxdqcc05Hk',
    appId: '1:1048947692024:android:b22881189650487128860d',
    messagingSenderId: '1048947692024',
    projectId: 'test-ff414',
    storageBucket: 'test-ff414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrO5uUXlGImgDVhkvBRmngrFWCEaljkx4',
    appId: '1:1048947692024:ios:48f14c8558201a6b28860d',
    messagingSenderId: '1048947692024',
    projectId: 'test-ff414',
    storageBucket: 'test-ff414.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrO5uUXlGImgDVhkvBRmngrFWCEaljkx4',
    appId: '1:1048947692024:ios:48f14c8558201a6b28860d',
    messagingSenderId: '1048947692024',
    projectId: 'test-ff414',
    storageBucket: 'test-ff414.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );
}
